import About from '@/components/About';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Head from 'next/head';

export default function Home() {
	const style = {
		wrapper: `bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0`,
		hero: `snap-start`,
		about: `snap-center`,
	};

	return (
		<div className={style.wrapper}>
			<Head>
				<title>Pham Minh Tan's Portfolio</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				{/* <meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/> */}
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<Header />

			{/* Hero */}
			<section
				id="hero"
				className={style.hero}>
				<Hero />
			</section>

			{/* About */}
			<section className={style.about}>
				<About />
			</section>
			{/* Experience */}
			{/* Skills */}
			{/* Projects */}
			{/* Contact */}
		</div>
	);
}
